language: python
install: make minimal
script: make test
after_success: venv/bin/coveralls
sudo: false
cache:
    directories:
        - $HOME/venv
        - $HOME/.pip
        - $HOME/.pre-commit
        - $HOME/.cache
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.4-dev
