language: python
install: make minimal
script: make test
sudo: false
cache:
    directories:
        - $HOME/venv
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.4-dev
